version: '3.4'

services:
  fishmarket.ui:
    image: ${DOCKER_REGISTRY-}fishmarket
    build:
      context: .
      dockerfile: FishMarket.UI/Dockerfile

  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest